deployKubeScheduler: False
deployKubeControllerManager: False
deployKubeDNS: False

exporter-kubelets:
  # Set to false for Azure
  https: false # enable kubelet for nodes, note that 3 targets will be down since we don't have access to the masters

grafana:
  service:
    type: LoadBalancer
    loadBalancerIP: "51.144.126.90" # static AKS LB IP
  image:
    tag: 5.3.2
  serverDashboardConfigmaps:
    - custom-dashboards
    - custom-datasources
  extraVars:
  - name: GF_INSTALL_PLUGINS
    value: "grafana-azure-monitor-datasource,digrich-bubblechart-panel,grafana-clock-panel,grafana-piechart-panel,jdbranham-diagram-panel"
