apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ index .Values.serverDashboardConfigmaps 1 }}
data:
{{ (.Files.Glob "custom-datasources/*.json").AsConfig | indent 2 }}